### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by Mardonis** [luka-zitnik/jshint-for-netbeans#1]
After I had installed the plugin, I went to the Tools | Options | Editor area to check it out, and during the process this error popped up. Thank you for the plugin.

java.lang.NullPointerException
    at lukazitnik.jshint.annotations.LintingThread.<init>(LintingThread.java:22)
    at lukazitnik.jshint.annotations.JSHintDocumentListener.updateAnnotations(JSHintDocumentListener.java:32)
    at lukazitnik.jshint.annotations.EditorRegistryListener.addDocumentListenerAndAnnotations(EditorRegistryListener.java:87)
    at lukazitnik.jshint.annotations.EditorRegistryListener.updateOpenDocuments(EditorRegistryListener.java:64)
    at lukazitnik.jshint.Installer.updateChangeListenersOnEditorRegistry(Installer.java:46)
    at lukazitnik.jshint.Installer.access$000(Installer.java:13)
    at lukazitnik.jshint.Installer$1.preferenceChange(Installer.java:35)
[catch] at java.util.prefs.AbstractPreferences$EventDispatchThread.run(AbstractPreferences.java:1496)

**Comment by luka-zitnik** [comment]
What a nasty stack trace! I am truly sorry you've encountered it. It looks like the editor module doesn't behave as I expected. I would like to know more about the environment in which the plugin is ran. If it's not too much to ask, could you please send me your IDE log file? You can get it by going to **Main Menu -> View -> IDE Log** and then **Output Window -> IDE Log -> Ctrl+S**.

**Comment by luka-zitnik** [comment]
Version 1.1.2 of the plugin bears a fix for this issue. It can be downloaded from the [NetBeans Plugin Portal](http://plugins.netbeans.org/PluginPortal/). Thank you for this report.
