### ISSUE TITLE
Thread Death

### ISSUE THREAD

**Issue by Mardonis** [luka-zitnik/jshint-for-netbeans#3]
Hello,

I have been using your plugin for sometime now in Netbeans and it's working great. Today I came across an error that said Thread Death. Here is the crash. and the netbeans info I am running. If there is anymore info you need just let me know. Almost forgot i am running your latest version of jshint. "1446505179_lukazitnik-jshint.nbm"

Product Version: NetBeans IDE 8.1 RC (Build 201510012201)
Java: 1.8.0_45; Java HotSpot(TM) Client VM 25.45-b02
Runtime: Java(TM) SE Runtime Environment 1.8.0_45-b14
System: Windows 7 version 6.1 running on x86; Cp1252; en_US (nb)

java.lang.ThreadDeath
    at java.lang.Thread.stop(Thread.java:850)
    at lukazitnik.jshint.annotations.LintingThread.stopAndFinishProgressHandle(LintingThread.java:55)
    at lukazitnik.jshint.annotations.JSHintDocumentListener.updateAnnotations(JSHintDocumentListener.java:29)
    at lukazitnik.jshint.annotations.JSHintDocumentListener.insertUpdate(JSHintDocumentListener.java:13)
    at org.netbeans.lib.editor.util.swing.PriorityDocumentListenerList.insertUpdate(PriorityDocumentListenerList.java:85)
    at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
    at org.netbeans.editor.BaseDocument.fireInsertUpdate(BaseDocument.java:1624)
    at org.netbeans.editor.BaseDocument.handleInsertString(BaseDocument.java:823)
    at org.netbeans.editor.BaseDocument$FilterBypassImpl.insertString(BaseDocument.java:2587)
    at javax.swing.text.DocumentFilter.insertString(DocumentFilter.java:100)
    at org.openide.text.CloneableEditorSupport$DocFilter.insertString(CloneableEditorSupport.java:2367)
    at org.netbeans.editor.BaseDocument.insertString(BaseDocument.java:749)
    at org.netbeans.editor.BaseKit$DefaultKeyTypedAction.insertString(BaseKit.java:1226)
    at org.netbeans.modules.csl.core.CslEditorKit$GsfDefaultKeyTypedAction.insertString(CslEditorKit.java:271)
    at org.netbeans.editor.BaseKit$DefaultKeyTypedAction.performTextInsertion(BaseKit.java:1292)
    at org.netbeans.editor.BaseKit$DefaultKeyTypedAction.access$100(BaseKit.java:1057)
    at org.netbeans.editor.BaseKit$DefaultKeyTypedAction$2.run(BaseKit.java:1160)
    at org.netbeans.editor.GuardedDocument.runAtomicAsUser(GuardedDocument.java:356)
    at org.netbeans.editor.BaseKit$DefaultKeyTypedAction.actionPerformed(BaseKit.java:1136)
    at org.netbeans.editor.ext.ExtKit$ExtDefaultKeyTypedAction.actionPerformed(ExtKit.java:1024)
    at org.netbeans.modules.csl.core.CslEditorKit$GsfDefaultKeyTypedAction.actionPerformed(CslEditorKit.java:254)
    at org.netbeans.editor.BaseAction.actionPerformed(BaseAction.java:339)
    at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
    at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
    at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
    at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
    at java.awt.Component.processEvent(Component.java:6302)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
    at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
    at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
    at java.awt.Component.dispatchEventImpl(Component.java:4752)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[catch] at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by luka-zitnik** [comment]
I do cut linting when there's another change in the file and the file needs to be linted again. I only don't remember I made it evident like this. I'll have to handle it properly. Thank you for reporting this issue.

**Comment by luka-zitnik** [comment]
How often does this happen?

**Comment by Mardonis** [comment]
I just happened to see it pop up that one time but I'll let you know if it does it again. Thank you for looking into this.

**Comment by luka-zitnik** [comment]
Yes, please, do let me know. I am willing to work in the meantime on a new
version that will "throttle" instead of stop linting threads.

**Comment by luka-zitnik** [comment]
Version 1.1.5 is available for download from the NetBeans Plugin Portal, http://plugins.netbeans.org/plugin/57838/jshint-for-netbeans.
